extends Node

enum MouseMode { 
	VISIBLE = Input.MOUSE_MODE_VISIBLE,
	CONFINED = Input.MOUSE_MODE_CONFINED,
	CAPTURED = Input.MOUSE_MODE_CAPTURED,
	HIDDEN = Input.MOUSE_MODE_HIDDEN,
	CONFINED_HIDDEN = Input.MOUSE_MODE_CONFINED_HIDDEN,
}
